#pragma once

#define FST_TINY 5, \
	FST::NODE(1, FST::RELATION('t', 1)),\
	FST::NODE(1, FST::RELATION('i', 2)),\
	FST::NODE(1, FST::RELATION('n', 3)),\
	FST::NODE(1, FST::RELATION('y', 4)),\
	FST::NODE()

#define FST_SYMBOLIC 9, \
	FST::NODE(1, FST::RELATION('s', 1)),\
	FST::NODE(1, FST::RELATION('y', 2)),\
	FST::NODE(1, FST::RELATION('m', 3)),\
	FST::NODE(1, FST::RELATION('b', 4)),\
	FST::NODE(1, FST::RELATION('o', 5)),\
	FST::NODE(1, FST::RELATION('l', 6)),\
	FST::NODE(1, FST::RELATION('i', 7)),\
	FST::NODE(1, FST::RELATION('c', 8)),\
	FST::NODE()

#define FST_LOGICAL 8, \
	FST::NODE(1, FST::RELATION('l', 1)),\
	FST::NODE(1, FST::RELATION('o', 2)),\
	FST::NODE(1, FST::RELATION('g', 3)),\
	FST::NODE(1, FST::RELATION('i', 4)),\
	FST::NODE(1, FST::RELATION('c', 5)),\
	FST::NODE(1, FST::RELATION('a', 6)),\
	FST::NODE(1, FST::RELATION('l', 7)),\
	FST::NODE()

#define FST_FUNC 5, \
    FST::NODE(1, FST::RELATION('f', 1)), \
    FST::NODE(1, FST::RELATION('u', 2)), \
    FST::NODE(1, FST::RELATION('n', 3)), \
    FST::NODE(1, FST::RELATION('c', 4)), \
    FST::NODE()

#define FST_SET 4, \
    FST::NODE(1, FST::RELATION('s', 1)), \
    FST::NODE(1, FST::RELATION('e', 2)), \
    FST::NODE(1, FST::RELATION('t', 3)), \
    FST::NODE()

#define FST_GIVEBACK 9, \
	FST::NODE(1, FST::RELATION('g', 1)),\
	FST::NODE(1, FST::RELATION('i', 2)),\
	FST::NODE(1, FST::RELATION('v', 3)),\
	FST::NODE(1, FST::RELATION('e', 4)),\
	FST::NODE(1, FST::RELATION('b', 5)),\
	FST::NODE(1, FST::RELATION('a', 6)),\
	FST::NODE(1, FST::RELATION('c', 7)),\
	FST::NODE(1, FST::RELATION('k', 8)),\
	FST::NODE()

#define FST_SHOW 5, \
	FST::NODE(1, FST::RELATION('s', 1)),\
	FST::NODE(1, FST::RELATION('h', 2)),\
	FST::NODE(1, FST::RELATION('o', 3)),\
	FST::NODE(1, FST::RELATION('w', 4)),\
	FST::NODE()

#define FST_LIB 4, \
	FST::NODE(1, FST::RELATION('z', 1)),\
	FST::NODE(1, FST::RELATION('e', 2)),\
	FST::NODE(1, FST::RELATION('i', 3)),\
	FST::NODE()

#define FST_WHEN 5, \
   FST::NODE(1, FST::RELATION('w',1)),\
   FST::NODE(1, FST::RELATION('h',2)),\
   FST::NODE(1, FST::RELATION('e',3)),\
   FST::NODE(1, FST::RELATION('n',4)),\
   FST::NODE()

#define FST_OTHERWISE 10, \
	FST::NODE(1, FST::RELATION('o', 1)),\
	FST::NODE(1, FST::RELATION('t', 2)),\
	FST::NODE(1, FST::RELATION('h', 3)),\
	FST::NODE(1, FST::RELATION('e', 4)),\
	FST::NODE(1, FST::RELATION('r', 5)),\
	FST::NODE(1, FST::RELATION('w', 6)),\
	FST::NODE(1, FST::RELATION('i', 7)),\
	FST::NODE(1, FST::RELATION('s', 8)),\
	FST::NODE(1, FST::RELATION('e', 9)),\
	FST::NODE()

#define FST_SYMBLEN 8,\
    FST::NODE(1, FST::RELATION('s',1)),\
    FST::NODE(1, FST::RELATION('y',2)),\
    FST::NODE(1, FST::RELATION('m',3)),\
    FST::NODE(1, FST::RELATION('b',4)),\
    FST::NODE(1, FST::RELATION('l',5)),\
    FST::NODE(1, FST::RELATION('e',6)),\
    FST::NODE(1, FST::RELATION('n',7)),\
    FST::NODE()

#define FST_SYMBTOTINY 11,\
    FST::NODE(1, FST::RELATION('s',1)),\
    FST::NODE(1, FST::RELATION('y',2)),\
    FST::NODE(1, FST::RELATION('m',3)),\
    FST::NODE(1, FST::RELATION('b',4)),\
    FST::NODE(1, FST::RELATION('t',5)),\
    FST::NODE(1, FST::RELATION('o',6)),\
    FST::NODE(1, FST::RELATION('t',7)),\
    FST::NODE(1, FST::RELATION('i',8)),\
    FST::NODE(1, FST::RELATION('n',9)),\
    FST::NODE(1, FST::RELATION('y',10)),\
    FST::NODE()

#define FST_ID 2, \
	FST::NODE(52, \
	FST::RELATION('a', 0), FST::RELATION('b', 0), FST::RELATION('c', 0), FST::RELATION('d', 0), FST::RELATION('e', 0), FST::RELATION('f', 0),\
	FST::RELATION('g', 0), FST::RELATION('h', 0), FST::RELATION('i', 0), FST::RELATION('j', 0), FST::RELATION('k', 0), FST::RELATION('l', 0),\
	FST::RELATION('m', 0), FST::RELATION('n', 0), FST::RELATION('o', 0), FST::RELATION('p', 0), FST::RELATION('q', 0), FST::RELATION('r', 0),\
	FST::RELATION('s', 0), FST::RELATION('t', 0), FST::RELATION('u', 0), FST::RELATION('v', 0), FST::RELATION('w', 0), FST::RELATION('x', 0),\
	FST::RELATION('y', 0), FST::RELATION('z', 0),\
	\
	FST::RELATION('a', 1), FST::RELATION('b', 1), FST::RELATION('c', 1), FST::RELATION('d', 1), FST::RELATION('e', 1), FST::RELATION('f', 1),\
	FST::RELATION('g', 1), FST::RELATION('h', 1), FST::RELATION('i', 1), FST::RELATION('j', 1), FST::RELATION('k', 1), FST::RELATION('l', 1),\
	FST::RELATION('m', 1), FST::RELATION('n', 1), FST::RELATION('o', 1), FST::RELATION('p', 1), FST::RELATION('q', 1), FST::RELATION('r', 1),\
	FST::RELATION('s', 1), FST::RELATION('t', 1), FST::RELATION('u', 1), FST::RELATION('v', 1), FST::RELATION('w', 1), FST::RELATION('x', 1),\
	FST::RELATION('y', 1), FST::RELATION('z', 1)),\
    FST::NODE()

#define FST_TINYLITERAL10 2, \
	FST::NODE(20, \
	FST::RELATION('1', 0), FST::RELATION('2', 0), FST::RELATION('3', 0), FST::RELATION('4', 0), FST::RELATION('5', 0), FST::RELATION('6', 0),\
	FST::RELATION('7', 0), FST::RELATION('8', 0), FST::RELATION('9', 0),\
	\
	FST::RELATION('1', 1), FST::RELATION('2', 1), FST::RELATION('3', 1), FST::RELATION('4', 1), FST::RELATION('5', 1), FST::RELATION('6', 1),\
	FST::RELATION('7', 1), FST::RELATION('8', 1), FST::RELATION('9', 1), FST::RELATION('0', 1)),\
	FST::NODE()

#define FST_TINYLITERAL8 3, \
	FST::NODE(1, FST::RELATION('0', 1)),  \
	FST::NODE(16, \
	FST::RELATION('1', 1), FST::RELATION('1', 1), FST::RELATION('3', 1), FST::RELATION('4', 1), FST::RELATION('5', 1), FST::RELATION('6', 1),\
	FST::RELATION('7', 1), FST::RELATION('0', 1),\
	\
	FST::RELATION('1', 2), FST::RELATION('2', 2), FST::RELATION('3', 2), FST::RELATION('4', 2), FST::RELATION('5', 2), FST::RELATION('6', 2),\
	FST::RELATION('7', 2), FST::RELATION('0', 2)),\
	FST::NODE()

//#define FST_TINYLITERAL16 3, \
//	FST::NODE(1, FST::RELATION('0', 1)),  \
//	FST::NODE(2, FST::RELATION('x', 2), FST::RELATION('X', 2)),  \
//	FST::NODE(32, \
//	FST::RELATION('0', 2), FST::RELATION('1', 2), FST::RELATION('1', 2), FST::RELATION('3', 2), FST::RELATION('4', 2), FST::RELATION('5', 2), FST::RELATION('6', 2),\
//	FST::RELATION('7', 2), FST::RELATION('8', 2), FST::RELATION('9',2), FST::RELATION('A', 2), FST::RELATION('B',2), FST::RELATION('C',2), FST::RELATION('D',2), FST::RELATION('E',2), FST::RELATION('F',2),\
//	\
//	FST::RELATION('0', 3), FST::RELATION('1', 3), FST::RELATION('2', 3), FST::RELATION('3', 3), FST::RELATION('4', 3), FST::RELATION('5', 3), FST::RELATION('6', 3),\
//	FST::RELATION('7', 3), FST::RELATION('8', 3), FST::RELATION('9', 3), FST::RELATION('A', 3), FST::RELATION('B', 3), FST::RELATION('C', 3), FST::RELATION('D', 3), FST::RELATION('E', 3), FST::RELATION('F', 3)),\
//	FST::NODE()

//TODO: LAN loop
#define FST_SYMBOLICLITERAL 4, \
	FST::NODE(1, FST::RELATION('"', 1)),\
	FST::NODE(156, \
	FST::RELATION('a', 1), FST::RELATION('b', 1), FST::RELATION('c', 1), FST::RELATION('d', 1), FST::RELATION('e', 1), FST::RELATION('f', 1),\
	FST::RELATION('g', 1), FST::RELATION('h', 1), FST::RELATION('i', 1), FST::RELATION('j', 1), FST::RELATION('k', 1), FST::RELATION('l', 1),\
	FST::RELATION('m', 1), FST::RELATION('n', 1), FST::RELATION('o', 1), FST::RELATION('p', 1), FST::RELATION('q', 1), FST::RELATION('r', 1),\
	FST::RELATION('s', 1), FST::RELATION('t', 1), FST::RELATION('u', 1), FST::RELATION('v', 1), FST::RELATION('w', 1), FST::RELATION('x', 1),\
	FST::RELATION('y', 1), FST::RELATION('z', 1), FST::RELATION('1', 1), FST::RELATION('2', 1), FST::RELATION('3', 1), FST::RELATION('4', 1),\
	FST::RELATION('5', 1), FST::RELATION('6', 1), FST::RELATION('7', 1), FST::RELATION('8', 1), FST::RELATION('9', 1), FST::RELATION('0', 1),\
	\
	FST::RELATION('à', 1), FST::RELATION('á', 1), FST::RELATION('â', 1), FST::RELATION('ã', 1), FST::RELATION('ä', 1), FST::RELATION('å', 1),\
	FST::RELATION('¸', 1), FST::RELATION('æ', 1), FST::RELATION('ç', 1), FST::RELATION('è', 1), FST::RELATION('é', 1), FST::RELATION('ê', 1),\
	FST::RELATION('ë', 1), FST::RELATION('ì', 1), FST::RELATION('í', 1), FST::RELATION('î', 1), FST::RELATION('ï', 1), FST::RELATION('ð', 1),\
	FST::RELATION('ñ', 1), FST::RELATION('ò', 1), FST::RELATION('ó', 1), FST::RELATION('ô', 1), FST::RELATION('õ', 1), FST::RELATION('ö', 1),\
	FST::RELATION('÷', 1), FST::RELATION('ø', 1), FST::RELATION('ù', 1), FST::RELATION('ú', 1), FST::RELATION('û', 1), FST::RELATION('ü', 1),\
	FST::RELATION('ý', 1), FST::RELATION('þ', 1), FST::RELATION('ÿ', 1), FST::RELATION(' ', 1), FST::RELATION('.', 1), FST::RELATION(',', 1),\
	FST::RELATION('?', 1), FST::RELATION('!', 1), FST::RELATION(';', 1), FST::RELATION(':', 1), FST::RELATION('-', 1), FST::RELATION('\t', 1),\
	\
	FST::RELATION('a', 2), FST::RELATION('b', 2), FST::RELATION('c', 2), FST::RELATION('d', 2), FST::RELATION('e', 2), FST::RELATION('f', 2),\
	FST::RELATION('g', 2), FST::RELATION('h', 2), FST::RELATION('i', 2), FST::RELATION('j', 2), FST::RELATION('k', 2), FST::RELATION('l', 2),\
	FST::RELATION('m', 2), FST::RELATION('n', 2), FST::RELATION('o', 2), FST::RELATION('p', 2), FST::RELATION('q', 2), FST::RELATION('r', 2),\
	FST::RELATION('s', 2), FST::RELATION('t', 2), FST::RELATION('u', 2), FST::RELATION('v', 2), FST::RELATION('w', 2), FST::RELATION('x', 2),\
	FST::RELATION('y', 2), FST::RELATION('z', 2), FST::RELATION('1', 2), FST::RELATION('2', 2), FST::RELATION('3', 2), FST::RELATION('4', 2),\
	FST::RELATION('5', 2), FST::RELATION('6', 2), FST::RELATION('7', 2), FST::RELATION('8', 2), FST::RELATION('9', 2), FST::RELATION('0', 2),\
	\
	FST::RELATION('à', 2), FST::RELATION('á', 2), FST::RELATION('â', 2), FST::RELATION('ã', 2), FST::RELATION('ä', 2), FST::RELATION('å', 2),\
	FST::RELATION('¸', 2), FST::RELATION('æ', 2), FST::RELATION('ç', 2), FST::RELATION('è', 2), FST::RELATION('é', 2), FST::RELATION('ê', 2),\
	FST::RELATION('ë', 2), FST::RELATION('ì', 2), FST::RELATION('í', 2), FST::RELATION('î', 2), FST::RELATION('ï', 2), FST::RELATION('ð', 2),\
	FST::RELATION('ñ', 2), FST::RELATION('ò', 2), FST::RELATION('ó', 2), FST::RELATION('ô', 2), FST::RELATION('õ', 2), FST::RELATION('ö', 2),\
	FST::RELATION('÷', 2), FST::RELATION('ø', 2), FST::RELATION('ù', 2), FST::RELATION('ú', 2), FST::RELATION('û', 2), FST::RELATION('ü', 2),\
	FST::RELATION('ý', 2), FST::RELATION('þ', 2), FST::RELATION('ÿ', 2), FST::RELATION(' ', 2), FST::RELATION('.', 2), FST::RELATION(',', 2),\
	FST::RELATION('?', 2), FST::RELATION('!', 2), FST::RELATION(';', 2), FST::RELATION(':', 2), FST::RELATION('-', 2), FST::RELATION('\t', 2)),\
    \
	FST::NODE(1, FST::RELATION('"', 3)),\
	FST::NODE()

#define FST_TRUE 5,\
    FST::NODE(1, FST::RELATION('t',1)),\
    FST::NODE(1, FST::RELATION('r',2)),\
    FST::NODE(1, FST::RELATION('u',3)),\
    FST::NODE(1, FST::RELATION('e',4)),\
    FST::NODE()

#define FST_FALSE 6,\
    FST::NODE(1, FST::RELATION('f',1)),\
    FST::NODE(1, FST::RELATION('a',2)),\
    FST::NODE(1, FST::RELATION('l',3)),\
    FST::NODE(1, FST::RELATION('s',4)),\
    FST::NODE(1, FST::RELATION('e',5)),\
    FST::NODE()

#define FST_EXCLAMATION 2,\
    FST::NODE(1, FST::RELATION('!',1)),\
    FST::NODE()

#define FST_POINT 2,\
    FST::NODE(1, FST::RELATION('.',1)),\
    FST::NODE()

#define FST_COMMA 2,\
    FST::NODE(1, FST::RELATION(',',1)),\
    FST::NODE()

#define FST_LEFTBRACE 2,\
    FST::NODE(1, FST::RELATION('[',1)),\
    FST::NODE()

#define FST_RIGHTBRACE 2,\
    FST::NODE(1, FST::RELATION(']',1)),\
    FST::NODE()

#define FST_LEFTHESIS 2,	\
	FST::NODE(1, FST::RELATION('(', 1)),\
	FST::NODE()

#define FST_RIGHTHESIS 2,	\
	FST::NODE(1, FST::RELATION(')', 1)),\
	FST::NODE()

//#define FST_MORE 2, \
//   FST::NODE(1, FST::RELATION('>', 1)),\
//   FST::NODE()
//
//#define FST_LESS 2, \
//   FST::NODE(1, FST::RELATION('<', 1)),\
//   FST::NODE()

#define FST_EQUALITY 2, \
   FST::NODE(1, FST::RELATION('=', 1)),\
   FST::NODE()

#define FST_COMPARE 2, \
   FST::NODE(1, FST::RELATION(':', 1)),\
   FST::NODE()

#define FST_PLUS 2, \
   FST::NODE(1, FST::RELATION('+', 1)),\
   FST::NODE()

#define FST_MINUS 2, \
  FST::NODE(1, FST::RELATION('-', 1)),\
  FST::NODE()

#define FST_STAR 2, \
  FST::NODE(1, FST::RELATION('*', 1)),\
  FST::NODE()

#define FST_SLASH 2, \
  FST::NODE(1, FST::RELATION('/', 1)),\
  FST::NODE()

#define FST_LEFTSHIFT 2, \
  FST::NODE(1, FST::RELATION('<', 1)),\
  FST::NODE()

#define FST_RIGHTSHIFT 2, \
  FST::NODE(1, FST::RELATION('>', 1)),\
  FST::NODE()